version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${TRACKS_DB:-tracks}
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: ..
      dockerfile: Dockerfile-3.0
    environment:
      # These are set in script/ci-build, so we need to pass-thru them.
      RAILS_ENV: $RAILS_ENV
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: root
      DATABASE_PASSWORD_EMPTY: 1
    volumes:
      - ${VOLUME:-..}:/app:Z
      - ${VOLUME:-..}/config/database.docker.yml:/app/config/database.yml:Z
      - ${VOLUME:-..}/config/site.docker.yml:/app/config/site.yml:Z
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db-data:
