version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-tracks}
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: ..
      dockerfile: Dockerfile-3.0
    environment:
      # These are set in script/ci-build, so we need to pass-thru them.
      RAILS_ENV: $RAILS_ENV
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_TYPE: postgresql
      DATABASE_ENCODING: unicode
      DATABASE_PORT: 5432
    volumes:
      - ${VOLUME:-..}:/app:Z
      - ${VOLUME:-..}/config/database.docker.yml:/app/config/database.yml:Z
      - ${VOLUME:-..}/config/site.docker.yml:/app/config/site.yml:Z
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db-data:
