#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

docker_compose="docker-compose --file docker-compose.yml"

echo "==> Building Docker image…"
$docker_compose build

echo "==> Building assets…"
bin/rake assets:precompile
