#!/bin/bash

set -e

docker_compose="docker-compose --file docker-compose.yml"

function cleanup() {
  $docker_compose down
}

function die() {
    echo $@
    exit 1
}

trap cleanup EXIT

export RAILS_ENV=test
export DATABASE_NAME=tracks_test

$docker_compose build
$docker_compose up -d
script/poll-for-db

# Leaving this in since it will be needed for Rails 5
$docker_compose run web bin/rails db:environment:set RAILS_ENV=test || true

$docker_compose run web bin/rake db:reset
$docker_compose run web bin/rake test

