#!/bin/bash
set -e

docker_compose="docker-compose --file docker-compose.yml"

function cleanup() {
  $docker_compose down
}

function die() {
    echo $@
    exit 1
}


trap cleanup EXIT

export RAILS_ENV=test
export TRACKS_DB=tracks_test

# Put a config/site.yml file in place since it's needed for operation
cp config/site.yml.tmpl config/site.yml

$docker_compose build
$docker_compose up -d
script/poll-for-db

# Leaving this in since it will be needed for Rails 5
bin/rails db:environment:set RAILS_ENV=test || true

bin/rake db:reset
bin/rake test

